Repository Jonathan-08/MangAnnuaire, pull requests merged in 2024-01, with the labels that each got.

#7 Ajout de la page shopping et modif du gitignore
  .gitignore
  index.html
  shopping.html
Labels: documentation

#14 Readme modif + lien du site
  Readme.md
Labels: documentation

#22 PB fix athors + music
  authors.html
  header.js
Labels: bug

#25 Ajout contact
  contact.html
  header.js
  style.css
Labels: enhancement

#27 Ajout de la page Animes
  anime.html
Labels: enhancement

#28 Ajout de la page manga et amélioration du fichier header.js
  header.js
  manga.html
Labels: enhancement

#31 modification
  header.js
  jeux_video.html
  style.css
Labels: enhancement
